# Generated by Django 2.2.3 on 2019-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_orders',
            name='cart',
            field=models.ManyToManyField(to='home.order', verbose_name='سبد خرید'),
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='home.order', verbose_name='سبد خرید'),
        ),
    ]
