# Generated by Django 2.2.3 on 2019-07-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190718_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'کاربر'},
        ),
    ]
