# Generated by Django 2.2.3 on 2019-07-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='برند')),
            ],
            options={
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع محصول')),
                ('unit', models.CharField(max_length=20, verbose_name='واحد اندازه گیری')),
            ],
            options={
                'verbose_name_plural': 'انواع محصولات',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(default='tools/default.jpg', upload_to='tools', verbose_name='تصویر')),
                ('sizes', models.CharField(blank=True, max_length=20, null=True, verbose_name='سایزها')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.types', verbose_name='نوع محصول')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brands', verbose_name='شرکت')),
            ],
            options={
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('ordered_amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
