# Generated by Django 2.2.3 on 2019-07-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_amount',
            new_name='amount',
        ),
    ]
