# Generated by Django 2.2.3 on 2019-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='tools/default.jpg', upload_to='tools'),
        ),
    ]
