# Generated by Django 2.2.3 on 2019-08-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190802_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='None', max_length=20, verbose_name='سایز'),
        ),
    ]
