# Generated by Django 2.2.3 on 2019-08-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190803_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='display_on_home',
            field=models.CharField(choices=[('بله', 'بله'), ('خیر', 'خیر')], default='بله', max_length=5, verbose_name='نمایش در صفحه اول'),
        ),
        migrations.AddField(
            model_name='types',
            name='display_on_home',
            field=models.CharField(choices=[('بله', 'بله'), ('خیر', 'خیر')], default='بله', max_length=5, verbose_name='نمایش در صفحه اول'),
        ),
    ]
