# Generated by Django 2.2.3 on 2019-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190810_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explain',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
