# Generated by Django 2.2.3 on 2019-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='explain',
            field=models.TextField(default='!توضیحی وجود ندارد', verbose_name='توضیحات'),
        ),
    ]
